<?php
namespace Rswork\Laravel\Cron\Console;

use Illuminate\Support\Str;

class GenerateCrontabCommand extends BaseCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'cron:generate {--all} {--base-path=} {--log-path=} {--default-run-user=} {--tz=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate crontab file from configured commands.';

    /**
     * Execute the console command.
     *
     * @return void
     * @throws \Exception
     */
    public function handle()
    {
        $commands = $this->getApplication()->all();
        $jobs = [];
        $defaultRunUser = $this->option('default-run-user') ?: 'webapp';

        foreach ($commands as $commandName => $command) {
            if (!($command instanceof BaseCommand)) {
                continue;
            }

            $cronJobs = $command->getCronJabs();

            if (!$cronJobs) {
                continue;
            }

            $env = $this->option('env') ?: config('app.env');
            $basePath = $this->option('base-path') ?: base_path();
            $logPath = $this->option('log-path') ?: $basePath . '/storage/logs';

            foreach ($cronJobs as $cronJob) {
                $type = isset($cronJob['type']) ? $cronJob['type'] : self::CRON_TYPE_CURRENT;
                $user = isset($cronJob['user']) ? $cronJob['user'] : $defaultRunUser;
                $logName = isset($cronJob['log_name']) ? $cronJob['log_name'] : $commandName;
                $job = null;

                $args = isset($cronJob['arguments']) ? implode(' ', $cronJob['arguments']) : '';

                switch ($type) {
                    case self::CRON_TYPE_CURRENT:
                        $job = "{$cronJob['schedule']} {$user} {$basePath}/artisan {$commandName}";

                        if ($args) {
                            $job .= " {$args}";
                        }

                        if ($env) {
                            $job .= " --env={$env}";
                        }
                        break;

                    case self::CRON_TYPE_SYSTEM:
                        if (!isset($cronJob['command'])) {
                            break;
                        }

                        if (!isset($cronJob['log_name'])) {
                            $logName = Str::slug($commandName);
                        }

                        $job = "{$cronJob['schedule']} {$user}";

                        if ($env) {
                            $job .= " LARAVEL_ENV={$env}";
                        }

                        $job .= " {$cronJob['command']}";

                        if ($args) {
                            $job .= " {$args}";
                        }
                        break;

                    case self::CRON_TYPE_ARTISAN:
                        if (!isset($cronJob['command'])) {
                            break;
                        }

                        $job = "{$cronJob['schedule']} {$user} {$basePath}/artisan {$cronJob['command']}";

                        if ($args) {
                            $job .= " {$args}";
                        }

                        if ($env) {
                            $job .= " --env={$env}";
                        }
                        break;

                    default:
                }

                if (!$job) {
                    continue;
                }

                $job .= " >> {$logPath}/{$logName}.log";
                $underEnv = empty($cronJob['env']) ? ['local'] : $cronJob['env'];

                if (in_array($env, $underEnv, false) || $this->option('all')) {
                    $jobs[] = "# {$commandName}(". get_class($command) . ") {$command->getDefinition()}";
                    $jobs[] = $job;
                    $jobs[] = '';
                }
            }
        }

        $tz = $this->option('tz') ?: date_default_timezone_get();

        $configs = [
            '# !!WARN!! DO NOT EDIT THIS FILE! PLEASE CONFIGURE CRONTAB IN LARAVEL COMMAND CLASS!',
            '',
            'CRON_TZ='.$tz,
            '',
            'SHELL=/bin/bash',
            'PATH=/sbin:/bin:/usr/sbin:/usr/bin',
            'MAILTO='.$defaultRunUser,
            'HOME=/',
            '',
            '# For details see man 4 crontabs',
            '',
            '# Example of job definition:',
            '# .---------------- minute (0 - 59)',
            '# |  .------------- hour (0 - 23)',
            '# |  |  .---------- day of month (1 - 31)',
            '# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...',
            '# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat',
            '# |  |  |  |  |',
            '# *  *  *  *  * user-name command to be executed',
            '',
        ];

        foreach (array_merge($configs, $jobs) as $item) {
            $this->line($item);
        }

        $this->line('');
        $this->line('# Generated by ' . $this->getName() . ' command');
    }
}
